### PR TITLE
Dockerize Nomenklatura

### PR DESCRIPTION
**Pull request by robbi5**
This PR contains a simple Dockerfile for running Nomenklatura with configuration from environment variables and a development environment with [fig](http://www.fig.sh).
`contrib/postgres-nk-hstore` is a docker container for a postgres that supports the required extensions `hstore` and `fuzzystrmatch`.

### CODE REVIEW

**Comment by pudo** [comment]
Do you think this is ready for a merge? I don't have time to test it today, but I'm surprised by how little configuration is required here. What about the JavaScript/CSS assets and bower dependencies, is all of that working fine?

**Comment by crccheck** [comment]
i didn't investigate what happened, but I did a `fig up` and got:
```
web_1      | sqlalchemy.exc.OperationalError: (OperationalError) could not translate host name "database" to address: Name or service not known

$ docker ps
CONTAINER ID        IMAGE                          COMMAND                CREATED              STATUS              PORTS                     NAMES
46bb79979ea3        nomenklatura_web:latest        "/app/contrib/docker   About a minute ago   Up About a minute   0.0.0.0:8080->8080/tcp    nomenklatura_web_1        
95ad2ed315dc        nomenklatura_database:latest   "/docker-entrypoint.   About a minute ago   Up About a minute   5432/tcp                  nomenklatura_database_1   
```

**Comment by robbi5** [comment]
> What about the JavaScript/CSS assets and bower dependencies, is all of that working fine?

Yep, they get loaded with bower in `contrib/docker-run.sh`.

> `could not translate host name "database" to address`

Okay, thats weird. What version of docker/fig on which OS are you using?

I tested it with docker 1.4.1 / fig 1.0.1 on ubuntu 14.04 and osx 10.10.2 (boot2docker 1.4.1). The output should look like this: https://gist.github.com/robbi5/c614ae673affdb36b69d

**Comment by crccheck** [comment]
I'm currently on fig 0.4.2, if I changed the fig config to use database_1, it worked. I also just upgraded fig (wow I hope they fixed all the things I didn't like about old fig) and your branch worked as is.

**Comment by robbi5** [comment]
I updated the PR, because [fig is now docker-compose](http://docs.docker.com/compose/).

**Comment by pudo** [comment]
Do you feel this should be merged? I hope to try it out soon, but would trust your judgement :)

**Comment by robbi5** [comment]
I'm using it daily for development, and we just tried it on @globalworming​s fresh docker/docker-compose installation. It works :)

**Comment by pudo** [comment]
Thanks so much, @robbi5 !!

**Comment by robbi5** [comment]
Yay \o/
Now it would be great if we could set up an [Docker Automated Build](http://docs.docker.com/docker-hub/builds/), so it would be available in the docker registry.

**Pull request merged**
